project_id = "jerpfhxijoapvbjcplua"

[functions.generate-toast]
verify_jwt = false

[functions.generate-feast-plan]
verify_jwt = false

[functions.tamada-ai]
verify_jwt = false

[functions.regenerate-library]
verify_jwt = false

[functions.tamada-external-api]
verify_jwt = false